name: 'Isaac XML File validator'
description: 'Checks the validity of all .xml files inside your Binding of Isaac mod files for both syntax and usage errors.'
author: "Wofsauge"
branding:
  icon: 'check'
  color: 'green'
inputs:
  rootFolder:
    description: 'Folder where the tool should search for .xml files'
    required: true
    default: '**'
  recursive:
    description: 'Should .xml files be searched recursively in the directory'
    required: false
    default: true
  expectedErrorCount:
    description: 'Number of validation errors that are expected to occur'
    required: false
    default: 0
  ignore:
    description: 'Files or folders that should be ignored by the tool.'
    required: false
    default: ''
  ignoreWarnings:
    description: 'If set to true, warnings will not count towards the number of errors.'
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
